kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: {{ include "fullname" . | trunc 60 }}-dc
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
rules:
    - apiGroups: ["cms.kyma-project.io"]
      resources: ["docstopics"]
      verbs: ["list"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: {{ template "fullname" . }}
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
rules:
    - apiGroups: ["servicecatalog.k8s.io"]
      resources: ["servicebrokers"]
      verbs: ["get", "list", "patch", "create", "delete"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs:     ["get"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "fullname" . }}
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "fullname" . | trunc 60 }}-dc
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: {{ template "fullname" . }}
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
subjects:
    - kind: ServiceAccount
      name: {{ template "fullname" . }}
      namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ template "fullname" . }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: {{ include "fullname" . | trunc 60 }}-dc
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
subjects:
    - kind: ServiceAccount
      name: {{ include "fullname" . | trunc 60 }}-dc
      namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "fullname" . | trunc 60 }}-dc