image: awsservicebroker/aws-servicebroker:beta
imagePullPolicy: IfNotPresent

authenticate: true
tls:
  cert:
  key:

deployClusterServiceBroker: false
deployNamespacedServiceBroker: true

region: us-east-1
bucket: awsservicebroker
key: templates/latest
s3region: us-east-1
tablename: awssb
brokerid: awsservicebroker
clusterDomain: cluster.local
prescribeoverrides: true
targetaccountid: ""
targetrolename: ""
vpcid: ""

brokerconfig:
  verbosity: 10

# Secret name where aws credentials are keep
# like "accesskeyid", "secretkey"
secretCredentialName: aws-broker-data

jobs:
  kubectlImage:
    repository: eu.gcr.io/kyma-project/develop/gcp-broker-provider
    tag: 237ba00f
    pullPolicy: IfNotPresent
