apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gcp-broker-provider.fullname" . }}-delete
  labels:
    app: {{ include "gcp-broker-provider.name" . }}
    chart: {{ include "gcp-broker-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ include "gcp-broker-provider.fullname" . }}
      restartPolicy: Never
      containers:
      - name: installer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["gcp-broker"]
        args: ["--action", "deprovision"]
        env:
        - name: RELEASE_NAME
          value: {{ .Release.Name }}
        - name: WORKING_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
