kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "gcp-broker-provider.fullname" . }}
  labels:
    app: {{ include "gcp-broker-provider.name" . }}
    chart: {{ include "gcp-broker-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "gcp-broker-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gcp-broker-provider.fullname" . }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "gcp-broker-provider.fullname" . }}-docu-checker
  labels:
    app: {{ include "gcp-broker-provider.name" . }}
    chart: {{ include "gcp-broker-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gcp-broker-provider.fullname" . }}-docu-checker
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gcp-broker-provider.fullname" . }}-docu-checker