apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcp-broker-provider.fullname" . }}
  labels:
    app: {{ include "gcp-broker-provider.name" . }}
    chart: {{ include "gcp-broker-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcp-broker-provider.fullname" . }}-docu-checker
  labels:
    app: {{ include "gcp-broker-provider.name" . }}
    chart: {{ include "gcp-broker-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}


